# Generated by Django 5.2.7 on 2025-11-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
