# Generated by Django 5.2.7 on 2025-11-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pickup_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Challenge title (e.g., 'Recycle 1 old phone')", max_length=200)),
                ('co2_saved', models.FloatField(help_text='CO2 saved in kg (e.g., 1.0)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this challenge to users?')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
